name: Create Service Folders

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq -y

    - name: Create folders
      run: |
        json=$(cat services.json)
        services=$(echo "$json" | jq -r '.services[] | @base64')
        for service in $services; do
          _jq() {
            echo ${service} | base64 --decode | jq -r ${1}
          }
          folder=$(_jq '.service_folder_name')
          url=$(_jq '.service_url')
          youtube_url=$(_jq '.service_youtube_url')
          mkdir "$folder"
          echo "- Service: $folder" > "$folder/README.md"
          echo -e "- Service URL: [$url]($url)\n\nYouTube URL: [$youtube_url]($youtube_url)" >> "$folder/README.md"
          echo -e "- [$folder]($folder/README.md)" >> README.md
        done
        git add .

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Create service folders and README files" --no-verify
        git status
        # Check the new content
        cat README.md

    - name: Create pull request
      if: github.event_name == 'workflow_dispatch'
      uses: peter-evans/create-pull-request@v3.10.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Updated service folders and README files'
        title: 'Updated service folders and README files'
        branch: ${{ github.ref }}
        body: 'This pull request updates the service folders and README files.'
